### ISSUE TITLE
SSH on the robots?

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#367]

**Comment by ar13pit** [comment]
My proposal is to setup a github account using the email address of AMIGO and add ssh-keys of the robots to that account

**Comment by Timple** [comment]
Tracability of who pushed what would be gone though.

**Comment by tue-robotics-robots** [comment]
Hi It is HERO.
Pushing is not important, committing is important.

**Comment by ar13pit** [comment]
I think we can still trace the commit authors by making sure that git config is reset on every power cycle and there is no global config so that who ever is committing will need to use git-su to set their identities locally to the repo.

**Comment by MatthijsBurgh** [comment]
This should be in git-hooks, isn't it @Timple

**Comment by reinzor** [comment]
> Hi It is HERO.
> Pushing is not important, committing is important.

Pushing is also important since this can be protected and commits can be faked. Anyway, I think these are two different topics:
- How to ensure proper commit authors
- What push authentication to use on a robot (why not use ssh keys and just take the keys with you when logging into a robot? Then you will always know who pushed. Or just stick with HTTPS auth, why is that not sufficient?)

**Comment by LoyVanBeek** [comment]
> * why not use ssh keys and just take the keys with you when logging into a robot

That would be ideal IMO. How is that done?

**Comment by LoyVanBeek** [comment]
HTTPS auth should actually be sufficient on the robots I think, especially when your credentials are remembered.

**Comment by reinzor** [comment]
> > * why not use ssh keys and just take the keys with you when logging into a robot
> 
> That would be ideal IMO. How is that done?

-A' Enables forwarding of the authentication agent connection. This can also be specified on a per-host basis in a configuration file.

https://linux.die.net/man/1/ssh

**Comment by LoyVanBeek** [comment]
So `sshamigo -A` should get you covered? If that gets incorporated into the alias, we're done?

**Comment by reinzor** [comment]
Yes, if:
- the keys on the host machines are correctly set-up 
- the repositories are configured to use ssh

**Comment by ar13pit** [comment]
> HTTPS auth should actually be sufficient on the robots I think, especially when your credentials are remembered.

@LoyVanBeek We removed the credentials caching functionality in tue-env-targets so that's not an option anymore unless you manually want to cache the credentials


> Pushing is also important since this can be protected and commits can be faked. Anyway, I think these are two different topics:
> 
> * How to ensure proper commit authors
> * What push authentication to use on a robot (why not use ssh keys and just take the keys with you when logging into a robot? Then you will always know who pushed. Or just stick with HTTPS auth, why is that not sufficient?)

@reinzor Do you also mean that we don't generate SSH keys for the robot and rather use our SSH keys to pull and push to github from the robot? Because that will break `tue-env` on the robot.

IMO the simplest solution is through git itself. If we alias git commit to a new command also called git commit which requires the user to supply his git-su credentials while executing the command and the wrapped command in-fact becomes:
`git commit --author="Credentials from git-su"`
we should be fine. Push logs will always say that the robot made the push but from commits the authors can easily be tracked.

**Comment by MatthijsBurgh** [comment]
> > HTTPS auth should actually be sufficient on the robots I think, especially when your credentials are remembered.
> 
> @LoyVanBeek We removed the credentials caching functionality in tue-env-targets so that's not an option anymore unless you manually want to cache the credentials

The caching function only setted the caching timeout. The caching itself is a part of the credential helper in git itself.

**Comment by LoyVanBeek** [comment]
To require a proper `git su`, there are pre-commit hooks. I think @Rayman had that set up once IIRC.

**Comment by MatthijsBurgh** [comment]
I create a github account for the robots. `HERO1` and `HERO2` are added to that account. I also extended all `ssh` commands with the `-A` option. So there are two ways of pushing.
