### ISSUE TITLE
Uninstalling target doesn't stop sourcing of setup

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#369]
Because the target file in the dependencies(-on) isn't removed, it's setup file is still sourced. This is a significant bug!

**Comment by ar13pit** [comment]
Well if the target is removed then the setup file doesn't exist anymore so what exactly is the issue?

**Comment by MatthijsBurgh** [comment]
Uninstalling, Title wasn't clear

**Comment by ar13pit** [comment]
I think I know how to solve this issue. The problem is in `tue-get` function of `tue-functions.bash` and not `tue-install-impl.bash`.

In the removal process we just go to the `installed` directory and delete the `target` file. What we must also do is first check if there exists any `target` file in `dependencies-on`. If exists, then do nothing. 

If does not exist then the following are the options:
1. Delete the `target` file in `dependencies` and run `tue-get update`. This will remove the setup file of `target` from `targets_setup.bash` but all the dependencies of `target` will still be in the workspace even though the only target they have dependencies on was `target`

2. Recursively read the `target` file in `dependencies` and for every dependency `target_parent` check if inside the `dependencies-on/$target_parent` there is something more than 'target'. If not then remove `$target_parent`. This will make sure that `target_parents` that have no children will be removed from the environment. 

In either of these options, the only thing that will be removed is the sourcing of packages in the environment and not the packages themselves.

@MatthijsBurgh @Timple is my analogy correct or am I missing something?

**Comment by MatthijsBurgh** [comment]
I ~don't like~ hate option 1.

You can only remove a target if not in list_installed and empty dependencies-on. Empty dependencies-on is not a guarantee.

**Comment by ar13pit** [comment]
Are you suggesting that if the `target` exists in `installed` and a removal command is issued, we also remove the children of this target that are listed in `dependencies-on/target` and then go for option 1? Because if we go for option 1 before removing the children, a lot of packages will break.

To summarize we have the following options:
**If a target exists in the installed list then** a removal has the following possibilities:
**If the target has no children then**
1. Only remove the target and not its single parents
2. Remove the target and its single parents as well

**If the target has children then**
3. Cancel the removal
4. Remove the children and then only remove the target
5. Remove the children, the target and the single parents of the target

@MatthijsBurgh You get to choose one option from (1, 2) and one from (3, 4, 5)

**Comment by MatthijsBurgh** [comment]
Fixed by #446
